<?php
/**
 * @file
 * Install, update and uninstall functions for the devel_generate_text_settings module.
 *
 */


/**
 * Implements hook_update_N().
 */
function devel_generate_text_settings_update_1000() {
  $config = config('devel_generate_text_settings.settings');
  $config->set('node_title_prefix', update_variable_get('devel_generate_text_settings_node_title_prefix', ''));
  $config->set('text_field_settings', update_variable_get('devel_generate_text_settings_node_text_settings', ''));
  update_variable_del('devel_generate_text_settings_node_title_prefix');
  update_variable_del('devel_generate_text_settings_node_text_settings');
}
